# Generated by Django 3.0.6 on 2020-05-30 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('number_payment', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_payment', models.CharField(blank=True, max_length=50, null=True, verbose_name='name_payment')),
                ('date_payment', models.DateTimeField(auto_now_add=True, verbose_name='date_payment')),
                ('sum_payment', models.IntegerField(blank=True, null=True, verbose_name='sum_payment')),
                ('status_payment', models.CharField(choices=[('AF', 'Active Full-time'), ('AP', 'Active Part-time'), ('LO', 'Laid Off'), ('RT', 'Retired'), ('TM', 'Terminated')], default='AF', max_length=20)),
            ],
        ),
    ]
